// The thesaurus store holds words with a similar meaning to each other,
// derived from WordNet's synsets (see public/data/thesaurus.tsv,
// generated by scripts/fetch-thesaurus.mjs).

import { normalizeWord } from "../wordStore/wordStore";

/** Where the thesaurus list lives, relative to the app's base URL. */
export const DEFAULT_THESAURUS_URL = `${import.meta.env.BASE_URL}data/thesaurus.tsv`;

export interface ThesaurusStore {
  /** Number of word/synonym pairs held in the store. */
  readonly size: number;
  /** Every known word sharing a similar meaning with `word` (case-insensitively). */
  findSynonyms(word: string): string[];
}

/**
 * Parses the thesaurus list file format: tab-separated `word\tsynonym`,
 * one per line, with blank lines and `#`-prefixed comment lines ignored.
 */
export function parseThesaurusList(raw: string): Map<string, string[]> {
  const entries = new Map<string, string[]>();
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }
    const [word, synonym] = trimmed.split("\t");
    if (!word || !synonym) {
      continue;
    }
    const existing = entries.get(word);
    if (existing) {
      existing.push(synonym);
    } else {
      entries.set(word, [synonym]);
    }
  }
  return entries;
}

export function createThesaurusStore(entries: Map<string, string[]>): ThesaurusStore {
  let size = 0;
  for (const synonyms of entries.values()) {
    size += synonyms.length;
  }

  return {
    size,
    findSynonyms(word: string) {
      return entries.get(normalizeWord(word)) ?? [];
    },
  };
}

/** Fetches and parses the thesaurus list, producing a ready-to-use ThesaurusStore. */
export async function loadThesaurusStore(
  url: string = DEFAULT_THESAURUS_URL,
): Promise<ThesaurusStore> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load thesaurus list from ${url}: ${response.status} ${response.statusText}`,
    );
  }
  const raw = await response.text();
  return createThesaurusStore(parseThesaurusList(raw));
}
