// The word store is Parsnipia's in-memory dictionary: a set of every word
// known to be valid, loaded from a plain-text word list (see
// public/data/words-en-gb.txt, generated by scripts/fetch-wordlist.mjs).

/** Where the word list lives, relative to the app's base URL. */
export const DEFAULT_WORD_LIST_URL = `${import.meta.env.BASE_URL}data/words-en-gb.txt`;

export interface WordStore {
  /** Number of words held in the store. */
  readonly size: number;
  /** Whether `word` (case-insensitively) is a known word. */
  has(word: string): boolean;
  /**
   * All known words matching `pattern` (case-insensitively), where `?`
   * matches any single letter. Matches must be the same length as
   * `pattern`. Returned in alphabetical order.
   */
  findMatches(pattern: string): string[];
  /**
   * All known words (case-insensitively) that can be formed by
   * rearranging `letters`, where `?` stands in for any single letter.
   * Matches must be the same length as `letters`. Returned in
   * alphabetical order.
   */
  findAnagrams(letters: string): string[];
}

/** A dictionary word found running contiguously through a sentence's letters. */
export interface HiddenWordMatch {
  word: string;
  /** Start index (inclusive) of the match in the original sentence. */
  start: number;
  /** End index (exclusive) of the match in the original sentence. */
  end: number;
}

/**
 * Normalizes user input for lookup/storage: trims surrounding whitespace
 * and lower-cases it. This does not validate that the result looks like a
 * word — callers that care should check that separately.
 */
export function normalizeWord(word: string): string {
  return word.trim().toLowerCase();
}

function escapeRegExpChar(char: string): string {
  return char.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Builds a regular expression matching words of the same shape as
 * `pattern`, where `?` stands in for any single letter.
 */
function patternToRegExp(pattern: string): RegExp {
  const source = pattern
    .split("")
    .map((char) => (char === "?" ? "." : escapeRegExpChar(char)))
    .join("");
  return new RegExp(`^${source}$`);
}

/** Counts occurrences of each character in `text`. */
function countLetters(text: string): Map<string, number> {
  const counts = new Map<string, number>();
  for (const char of text) {
    counts.set(char, (counts.get(char) ?? 0) + 1);
  }
  return counts;
}

/**
 * Whether `word` contains at least as many of each letter as `required`
 * calls for. An empty `required` (all wildcards) matches any word.
 */
function containsRequiredLetters(word: string, required: Map<string, number>): boolean {
  if (required.size === 0) {
    return true;
  }
  const wordCounts = countLetters(word);
  for (const [char, count] of required) {
    if ((wordCounts.get(char) ?? 0) < count) {
      return false;
    }
  }
  return true;
}

/**
 * Parses the word list file format: one lowercase word per line, with
 * blank lines and `#`-prefixed comment lines ignored.
 */
export function parseWordList(raw: string): Set<string> {
  const words = new Set<string>();
  for (const line of raw.split("\n")) {
    const word = line.trim();
    if (word === "" || word.startsWith("#")) {
      continue;
    }
    words.add(word);
  }
  return words;
}

export function createWordStore(words: Set<string>): WordStore {
  return {
    get size() {
      return words.size;
    },
    has(word: string) {
      return words.has(normalizeWord(word));
    },
    findMatches(pattern: string) {
      const normalized = normalizeWord(pattern);
      const regexp = patternToRegExp(normalized);
      const matches: string[] = [];
      for (const word of words) {
        if (word.length === normalized.length && regexp.test(word)) {
          matches.push(word);
        }
      }
      return matches.sort();
    },
    findAnagrams(letters: string) {
      const normalized = normalizeWord(letters);
      const required = countLetters(normalized.replace(/\?/g, ""));
      const matches: string[] = [];
      for (const word of words) {
        if (word.length === normalized.length && containsRequiredLetters(word, required)) {
          matches.push(word);
        }
      }
      return matches.sort();
    },
  };
}

/** Fetches and parses the word list, producing a ready-to-use WordStore. */
export async function loadWordStore(
  url: string = DEFAULT_WORD_LIST_URL,
): Promise<WordStore> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load word list from ${url}: ${response.status} ${response.statusText}`,
    );
  }
  const raw = await response.text();
  return createWordStore(parseWordList(raw));
}

/**
 * Finds every known word of exactly `length` letters that runs
 * contiguously through `sentence`'s letters once spaces and punctuation
 * are removed — e.g. "cat" is found in "the ca terrier" (spanning the
 * word break). Matches are returned left to right; `start`/`end` index
 * into the original `sentence` (not the letters-only version), covering
 * whatever spaces or punctuation the match happens to cross, so callers
 * can highlight the match in place.
 *
 * A match is excluded if it's simply one of the original whitespace-
 * separated words, unchanged — that word isn't *hidden*, it's just
 * sitting there as itself (e.g. "like" in "sounds like any mathematical
 * function" doesn't count, but "calf", spanning "mathemati**cal
 * f**unction", does).
 */
export function findHiddenWords(
  store: WordStore,
  sentence: string,
  length: number,
): HiddenWordMatch[] {
  if (!Number.isInteger(length) || length <= 0) {
    return [];
  }

  const letters: string[] = [];
  const positions: number[] = [];
  const runOfLetter: number[] = [];
  let currentRun = -1;
  let inRun = false;
  for (let i = 0; i < sentence.length; i++) {
    const char = sentence[i];
    if (/\s/.test(char)) {
      inRun = false;
      continue;
    }
    if (!inRun) {
      currentRun++;
      inRun = true;
    }
    if (/[a-zA-Z]/.test(char)) {
      letters.push(char.toLowerCase());
      positions.push(i);
      runOfLetter.push(currentRun);
    }
  }

  const matches: HiddenWordMatch[] = [];
  for (let start = 0; start + length <= letters.length; start++) {
    const end = start + length;
    const spansExactlyOneOriginalWord =
      runOfLetter[start] === runOfLetter[end - 1] &&
      (start === 0 || runOfLetter[start - 1] !== runOfLetter[start]) &&
      (end === letters.length || runOfLetter[end] !== runOfLetter[end - 1]);
    if (spansExactlyOneOriginalWord) {
      continue;
    }

    const candidate = letters.slice(start, end).join("");
    if (store.has(candidate)) {
      matches.push({
        word: candidate,
        start: positions[start],
        end: positions[end - 1] + 1,
      });
    }
  }
  return matches;
}
