// The word store is Parsnip's in-memory dictionary: a set of every word
// known to be valid, loaded from a plain-text word list (see
// public/data/words-en-gb.txt, generated by scripts/fetch-wordlist.mjs).

/** Where the word list lives, relative to the app's base URL. */
export const DEFAULT_WORD_LIST_URL = `${import.meta.env.BASE_URL}data/words-en-gb.txt`;

export interface WordStore {
  /** Number of words held in the store. */
  readonly size: number;
  /** Whether `word` (case-insensitively) is a known word. */
  has(word: string): boolean;
}

/**
 * Normalizes user input for lookup/storage: trims surrounding whitespace
 * and lower-cases it. This does not validate that the result looks like a
 * word — callers that care should check that separately.
 */
export function normalizeWord(word: string): string {
  return word.trim().toLowerCase();
}

/**
 * Parses the word list file format: one lowercase word per line, with
 * blank lines and `#`-prefixed comment lines ignored.
 */
export function parseWordList(raw: string): Set<string> {
  const words = new Set<string>();
  for (const line of raw.split("\n")) {
    const word = line.trim();
    if (word === "" || word.startsWith("#")) {
      continue;
    }
    words.add(word);
  }
  return words;
}

export function createWordStore(words: Set<string>): WordStore {
  return {
    get size() {
      return words.size;
    },
    has(word: string) {
      return words.has(normalizeWord(word));
    },
  };
}

/** Fetches and parses the word list, producing a ready-to-use WordStore. */
export async function loadWordStore(
  url: string = DEFAULT_WORD_LIST_URL,
): Promise<WordStore> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load word list from ${url}: ${response.status} ${response.statusText}`,
    );
  }
  const raw = await response.text();
  return createWordStore(parseWordList(raw));
}
