// The indicator store holds cryptic-crossword wordplay indicators: words
// and short phrases that, when spotted in a clue, suggest a particular
// kind of wordplay (anagram, hidden word, reversal, ...). Loaded from a
// tab-separated lookup file (see public/data/cryptic-indicators.tsv,
// generated by scripts/fetch-cryptic-indicators.mjs).

import {
  normalizePhrase,
  createPhraseLookup,
  findPhraseMatches,
  type PhraseLookup,
  type PhraseSpan,
} from "../phraseMatch/phraseMatch";

/** Where the indicator list lives, relative to the app's base URL. */
export const DEFAULT_INDICATOR_LIST_URL = `${import.meta.env.BASE_URL}data/cryptic-indicators.tsv`;

/** A one-line, plain-English description of each kind of wordplay. */
export const WORDPLAY_DESCRIPTIONS: Record<string, string> = {
  anagram: "The fenced-off letters are jumbled to spell the answer.",
  insertion: "One part of the wordplay is tucked inside another.",
  container: "One part of the wordplay wraps around another.",
  reversal: "Read backwards to get the answer, or part of it.",
  hidden: "The answer runs consecutively inside the surrounding words.",
  deletion: "A letter or letters are removed to leave the answer.",
  homophone: "The answer sounds like another word or phrase read aloud.",
  alternation: "Take alternating letters — e.g. every other one — from the surrounding words.",
};

/** Falls back to a generic note for any wordplay type not in WORDPLAY_DESCRIPTIONS. */
export function describeWordplay(wordplay: string): string {
  return WORDPLAY_DESCRIPTIONS[wordplay] ?? "This may be a cryptic wordplay indicator.";
}

/** One wordplay type an indicator phrase can suggest. */
export interface IndicatorMatch {
  wordplay: string;
  /** How many example clues in the source data used this phrase for this wordplay type. */
  count: number;
}

export interface IndicatorStore extends PhraseLookup<IndicatorMatch> {
  /** Number of (phrase, wordplay type) entries held in the store. */
  readonly size: number;
}

/**
 * Normalizes an indicator phrase (or a candidate substring pulled from a
 * clue) for lookup: trims, lower-cases, and collapses internal whitespace.
 */
export const normalizeIndicatorPhrase = normalizePhrase;

/**
 * Parses the indicator list file format: tab-separated
 * `indicator\twordplay\tcount`, one per line, with blank lines and
 * `#`-prefixed comment lines ignored.
 */
export function parseIndicatorList(raw: string): Map<string, IndicatorMatch[]> {
  const entries = new Map<string, IndicatorMatch[]>();
  for (const line of raw.split("\n")) {
    const trimmed = line.trim();
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }
    const [indicator, wordplay, countText] = trimmed.split("\t");
    if (!indicator || !wordplay) {
      continue;
    }
    const phrase = normalizeIndicatorPhrase(indicator);
    const count = Number.parseInt(countText ?? "", 10);
    const match: IndicatorMatch = { wordplay, count: Number.isFinite(count) ? count : 0 };
    const existing = entries.get(phrase);
    if (existing) {
      existing.push(match);
    } else {
      entries.set(phrase, [match]);
    }
  }
  return entries;
}

export function createIndicatorStore(entries: Map<string, IndicatorMatch[]>): IndicatorStore {
  let size = 0;
  for (const matches of entries.values()) {
    size += matches.length;
  }
  return { size, ...createPhraseLookup(entries) };
}

/** Fetches and parses the indicator list, producing a ready-to-use IndicatorStore. */
export async function loadIndicatorStore(
  url: string = DEFAULT_INDICATOR_LIST_URL,
): Promise<IndicatorStore> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(
      `Failed to load indicator list from ${url}: ${response.status} ${response.statusText}`,
    );
  }
  const raw = await response.text();
  return createIndicatorStore(parseIndicatorList(raw));
}

/** Splits a clue into its words, preserving their original text for display. */
export function tokenizeClue(clue: string): string[] {
  return clue.trim().split(/\s+/).filter(Boolean);
}

/** A candidate wordplay interpretation: `tokens[startWord..endWord)` may indicate `wordplay`. */
export interface ClueMatch extends IndicatorMatch, PhraseSpan {}

/**
 * Scans every contiguous run of `tokens` (up to `store.maxPhraseWords`
 * long) for known indicator phrases, returning one ClueMatch per
 * (span, wordplay type) hit — the same span can indicate more than one
 * kind of wordplay when the phrase is ambiguous, and spans can overlap.
 * Ordered with the most well-attested, longest indicators first.
 */
export function findIndicatorMatches(store: IndicatorStore, tokens: string[]): ClueMatch[] {
  return findPhraseMatches(
    store,
    tokens,
    (match, phrase, startWord, endWord) => ({ ...match, phrase, startWord, endWord }),
    (a, b) => b.count - a.count,
  );
}
