// Loads the test-suite report written by `npm test` (see vite.config.ts's
// `test.outputFile.json`) for the Tests page to render. Fetched at
// runtime rather than bundled at build time: the results file is
// regenerated by every `npm test` run, independently of `npm run build`,
// so a component that imported it as a static module could only ever
// show whatever happened to be on disk the last time the app was built
// — and would fail to build at all on a fresh clone before `npm test`
// has run once. A runtime fetch instead just shows "no results yet" in
// that case, and always reflects the latest run without a rebuild.

export interface TestAssertionResult {
  status: string;
  title: string;
  fullName?: string;
  failureMessages?: string[];
}

export interface TestFileResult {
  name: string;
  assertionResults: TestAssertionResult[];
}

export interface TestResultsData {
  numTotalTests: number;
  numPassedTests: number;
  numFailedTests: number;
  testResults: TestFileResult[];
  startTime?: number;
}

/** Where the generated test report lives, relative to the app's base URL. */
export const DEFAULT_RESULTS_URL = `${import.meta.env.BASE_URL}tests/results.json`;

const NO_RESULTS_MESSAGE = "No test results found yet. Run `npm test` to generate them.";

/**
 * Fetches and parses the test report. Any failure — a network error, a
 * non-ok response, or unparseable JSON — is reported as the same
 * friendly "no results yet" message, since from the page's point of
 * view they all mean the same thing: nobody has run the tests yet.
 */
export async function loadTestResults(
  url: string = DEFAULT_RESULTS_URL,
): Promise<TestResultsData> {
  let response: Response;
  try {
    response = await fetch(url, { cache: "no-store" });
  } catch {
    throw new Error(NO_RESULTS_MESSAGE);
  }
  if (!response.ok) {
    throw new Error(NO_RESULTS_MESSAGE);
  }
  try {
    return (await response.json()) as TestResultsData;
  } catch {
    throw new Error(NO_RESULTS_MESSAGE);
  }
}

/**
 * Shortens an absolute test file path down to the part from "tests/"
 * onwards, e.g. "/Users/.../tests/About/About.test.tsx" ->
 * "tests/About/About.test.tsx".
 */
export function relativePath(absolutePath: string): string {
  const marker = "/tests/";
  const index = absolutePath.lastIndexOf(marker);
  return index === -1 ? absolutePath : absolutePath.slice(index + 1);
}
